/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AstrologerSlugRouteImport } from './routes/astrologer.$slug'
import { Route as AdminAstrologersRouteImport } from './routes/admin.astrologers'
import { Route as AdminAstrologersIndexRouteImport } from './routes/admin.astrologers.index'
import { Route as ApiPublicConsultRouteImport } from './routes/api/public/consult'
import { Route as ApiPublicAuditPreviewRouteImport } from './routes/api/public/audit-preview'
import { Route as AdminAstrologersIdRouteImport } from './routes/admin.astrologers.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AstrologerSlugRoute = AstrologerSlugRouteImport.update({
  id: '/astrologer/$slug',
  path: '/astrologer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAstrologersRoute = AdminAstrologersRouteImport.update({
  id: '/astrologers',
  path: '/astrologers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAstrologersIndexRoute = AdminAstrologersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAstrologersRoute,
} as any)
const ApiPublicConsultRoute = ApiPublicConsultRouteImport.update({
  id: '/api/public/consult',
  path: '/api/public/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuditPreviewRoute = ApiPublicAuditPreviewRouteImport.update({
  id: '/api/public/audit-preview',
  path: '/api/public/audit-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAstrologersIdRoute = AdminAstrologersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAstrologersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/astrologers': typeof AdminAstrologersRouteWithChildren
  '/astrologer/$slug': typeof AstrologerSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/astrologers/$id': typeof AdminAstrologersIdRoute
  '/api/public/audit-preview': typeof ApiPublicAuditPreviewRoute
  '/api/public/consult': typeof ApiPublicConsultRoute
  '/admin/astrologers/': typeof AdminAstrologersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astrologer/$slug': typeof AstrologerSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/astrologers/$id': typeof AdminAstrologersIdRoute
  '/api/public/audit-preview': typeof ApiPublicAuditPreviewRoute
  '/api/public/consult': typeof ApiPublicConsultRoute
  '/admin/astrologers': typeof AdminAstrologersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/astrologers': typeof AdminAstrologersRouteWithChildren
  '/astrologer/$slug': typeof AstrologerSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/astrologers/$id': typeof AdminAstrologersIdRoute
  '/api/public/audit-preview': typeof ApiPublicAuditPreviewRoute
  '/api/public/consult': typeof ApiPublicConsultRoute
  '/admin/astrologers/': typeof AdminAstrologersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/astrologers'
    | '/astrologer/$slug'
    | '/admin/'
    | '/admin/astrologers/$id'
    | '/api/public/audit-preview'
    | '/api/public/consult'
    | '/admin/astrologers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/astrologer/$slug'
    | '/admin'
    | '/admin/astrologers/$id'
    | '/api/public/audit-preview'
    | '/api/public/consult'
    | '/admin/astrologers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/astrologers'
    | '/astrologer/$slug'
    | '/admin/'
    | '/admin/astrologers/$id'
    | '/api/public/audit-preview'
    | '/api/public/consult'
    | '/admin/astrologers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AstrologerSlugRoute: typeof AstrologerSlugRoute
  ApiPublicAuditPreviewRoute: typeof ApiPublicAuditPreviewRoute
  ApiPublicConsultRoute: typeof ApiPublicConsultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/astrologer/$slug': {
      id: '/astrologer/$slug'
      path: '/astrologer/$slug'
      fullPath: '/astrologer/$slug'
      preLoaderRoute: typeof AstrologerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/astrologers': {
      id: '/admin/astrologers'
      path: '/astrologers'
      fullPath: '/admin/astrologers'
      preLoaderRoute: typeof AdminAstrologersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/astrologers/': {
      id: '/admin/astrologers/'
      path: '/'
      fullPath: '/admin/astrologers/'
      preLoaderRoute: typeof AdminAstrologersIndexRouteImport
      parentRoute: typeof AdminAstrologersRoute
    }
    '/api/public/consult': {
      id: '/api/public/consult'
      path: '/api/public/consult'
      fullPath: '/api/public/consult'
      preLoaderRoute: typeof ApiPublicConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audit-preview': {
      id: '/api/public/audit-preview'
      path: '/api/public/audit-preview'
      fullPath: '/api/public/audit-preview'
      preLoaderRoute: typeof ApiPublicAuditPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/astrologers/$id': {
      id: '/admin/astrologers/$id'
      path: '/$id'
      fullPath: '/admin/astrologers/$id'
      preLoaderRoute: typeof AdminAstrologersIdRouteImport
      parentRoute: typeof AdminAstrologersRoute
    }
  }
}

interface AdminAstrologersRouteChildren {
  AdminAstrologersIdRoute: typeof AdminAstrologersIdRoute
  AdminAstrologersIndexRoute: typeof AdminAstrologersIndexRoute
}

const AdminAstrologersRouteChildren: AdminAstrologersRouteChildren = {
  AdminAstrologersIdRoute: AdminAstrologersIdRoute,
  AdminAstrologersIndexRoute: AdminAstrologersIndexRoute,
}

const AdminAstrologersRouteWithChildren =
  AdminAstrologersRoute._addFileChildren(AdminAstrologersRouteChildren)

interface AdminRouteChildren {
  AdminAstrologersRoute: typeof AdminAstrologersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAstrologersRoute: AdminAstrologersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AstrologerSlugRoute: AstrologerSlugRoute,
  ApiPublicAuditPreviewRoute: ApiPublicAuditPreviewRoute,
  ApiPublicConsultRoute: ApiPublicConsultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
