/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AstrologerSlugRouteImport } from './routes/astrologer.$slug'
import { Route as AdminAstrologersRouteImport } from './routes/admin.astrologers'
import { Route as ApiPublicConsultRouteImport } from './routes/api/public/consult'
import { Route as AdminAstrologersIdRouteImport } from './routes/admin.astrologers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologerSlugRoute = AstrologerSlugRouteImport.update({
  id: '/astrologer/$slug',
  path: '/astrologer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAstrologersRoute = AdminAstrologersRouteImport.update({
  id: '/admin/astrologers',
  path: '/admin/astrologers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConsultRoute = ApiPublicConsultRouteImport.update({
  id: '/api/public/consult',
  path: '/api/public/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAstrologersIdRoute = AdminAstrologersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAstrologersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/astrologers': typeof AdminAstrologersRouteWithChildren
  '/astrologer/$slug': typeof AstrologerSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/astrologers/$id': typeof AdminAstrologersIdRoute
  '/api/public/consult': typeof ApiPublicConsultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/astrologers': typeof AdminAstrologersRouteWithChildren
  '/astrologer/$slug': typeof AstrologerSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/astrologers/$id': typeof AdminAstrologersIdRoute
  '/api/public/consult': typeof ApiPublicConsultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/astrologers': typeof AdminAstrologersRouteWithChildren
  '/astrologer/$slug': typeof AstrologerSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/astrologers/$id': typeof AdminAstrologersIdRoute
  '/api/public/consult': typeof ApiPublicConsultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/astrologers'
    | '/astrologer/$slug'
    | '/admin/'
    | '/admin/astrologers/$id'
    | '/api/public/consult'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/astrologers'
    | '/astrologer/$slug'
    | '/admin'
    | '/admin/astrologers/$id'
    | '/api/public/consult'
  id:
    | '__root__'
    | '/'
    | '/admin/astrologers'
    | '/astrologer/$slug'
    | '/admin/'
    | '/admin/astrologers/$id'
    | '/api/public/consult'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAstrologersRoute: typeof AdminAstrologersRouteWithChildren
  AstrologerSlugRoute: typeof AstrologerSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicConsultRoute: typeof ApiPublicConsultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologer/$slug': {
      id: '/astrologer/$slug'
      path: '/astrologer/$slug'
      fullPath: '/astrologer/$slug'
      preLoaderRoute: typeof AstrologerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/astrologers': {
      id: '/admin/astrologers'
      path: '/admin/astrologers'
      fullPath: '/admin/astrologers'
      preLoaderRoute: typeof AdminAstrologersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/consult': {
      id: '/api/public/consult'
      path: '/api/public/consult'
      fullPath: '/api/public/consult'
      preLoaderRoute: typeof ApiPublicConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/astrologers/$id': {
      id: '/admin/astrologers/$id'
      path: '/$id'
      fullPath: '/admin/astrologers/$id'
      preLoaderRoute: typeof AdminAstrologersIdRouteImport
      parentRoute: typeof AdminAstrologersRoute
    }
  }
}

interface AdminAstrologersRouteChildren {
  AdminAstrologersIdRoute: typeof AdminAstrologersIdRoute
}

const AdminAstrologersRouteChildren: AdminAstrologersRouteChildren = {
  AdminAstrologersIdRoute: AdminAstrologersIdRoute,
}

const AdminAstrologersRouteWithChildren =
  AdminAstrologersRoute._addFileChildren(AdminAstrologersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAstrologersRoute: AdminAstrologersRouteWithChildren,
  AstrologerSlugRoute: AstrologerSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicConsultRoute: ApiPublicConsultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
